pipeline {
    agent any
    stages {
        when {
            changeset "api/**"
        }
        stage('Build') {
            steps{
                sh '''
                    #!/bin/bash

                    export PATH="$PATH:/usr/local/go/bin"

                    go version

                    go build -o demo .

                    ./demo    
                '''
            }
        }
    }
}
