pipeline {
    agent any
    stages {
        stage('Build') {
            when {
                changeset "api/**"
            }
            steps{
                sh '''
                    #!/bin/bash

                    export PATH="$PATH:/usr/local/go/bin"

                    go version

                    go build -o demo .

                    ./demo    
                '''
            }
        }
        stage('Parallel Stage') {
            when {
                changeset "api/**"
            }
            failFast true
            parallel {
                stage('cloud provider') {
                    stages {
                            stage('trigger local') {
                                steps {
                                    build job: 'local-demodemo', parameters: [string(name: 'GIT_BRANCH', value: "${env.GIT_BRANCH}")]
                                }
                            }
                            stage('Nested 2') {
                            steps {
                                echo "In stage Nested 2 within Branch C"
                            }
                        }
                    }
                }
            }
        }
    }
}
