pipeline {
    agent any
    stages {
        stage('Build') {
            when {
                changeset "api/**"
            }
            steps{
                sh '''
                    #!/bin/bash

                    export PATH="$PATH:/usr/local/go/bin"

                    go version

                    go build -o demo .

                    ./demo    
                '''
            }
        }
        stage('Parallel Stage') {
            when {
                branch 'main'
            }
            failFast true
            parallel {
                stage('providers') {
                    stages {
                            stage('Nested 1') {
                                steps {
                                    echo "In stage Nested 1 within Branch C"
                                }
                            }
                            stage('Nested 2') {
                            steps {
                                echo "In stage Nested 2 within Branch C"
                            }
                        }
                    }
                }
            }
        }
    }
}
